CONFIG_NETWORKING=y
CONFIG_NET_L2_OPENTHREAD=y

# Disable certain parts of Zephyr IPv6 stack
CONFIG_NET_IPV6_NBR_CACHE=n
CONFIG_NET_IPV6_MLD=n

# Logging
CONFIG_LOG=y
CONFIG_BOOT_BANNER=n
CONFIG_OPENTHREAD_DEBUG=y
CONFIG_OPENTHREAD_LOG_LEVEL_INFO=y

CONFIG_DEBUG=y
CONFIG_SHELL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_SERIAL=y

# Kernel options
CONFIG_MAIN_STACK_SIZE=20480
CONFIG_INIT_STACKS=y

# Increase logging thread stack size due to Spinel backend needs
CONFIG_LOG_PROCESS_THREAD_STACK_SIZE=20480
CONFIG_SHELL_STACK_SIZE=10240

# Set OpenThread Host architecture
CONFIG_OPENTHREAD_HOSTPROCESSOR=y
CONFIG_OPENTHREAD_SHELL=y
CONFIG_OPENTHREAD_FTD=y

CONFIG_OPENTHREAD_HOSTPROCESSOR_SPINEL_ON_GENERIC_SPI_DEV_NAME="SPI_DEV"

CONFIG_SPI=y
CONFIG_SPI_MCUX_LPSPI=y
CONFIG_SPI_GENERIC=y
